<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.3.1.min.js'))
        ?>
    </head>
    <body>
    <h1>Image Gallery</h1>

    <p>
    This page displays the list of uploaded images.
    </p>

    <p>
    <a href="<?= $this->url('images', ['action'=>'upload']); ?>" 
        class="btn btn-primary" role="button">Upload More</a>
    </p>

    <hr/>

    <?php if(count($files)==0): ?>

    <p>
    <i>There are no files to display.</i>
    </p>

    <?php else: ?>

    <div class="row">
    <div class="col-sm-6 col-md-12">

        <?php foreach($files as $file): ?>  

        <div class="img-thumbnail">
                
        <img src="<?= $this->url('images', ['action'=>'file'], 
                ['query'=>['name'=>$file, 'thumbnail'=>false]]); ?>">
                
        <div class="caption">
            <h3><?php echo $file; ?></h3>                    
            <p>
            <a target="_blank" href="<?= $this->url('images', ['action'=>'file'], 
            ['query'=>['name'=>$file]]); ?>" 
            class="btn btn-default" role="button">Show in Natural Size</a>
            <a href="<?= $this->url('images', ['action'=>'delete'], 
            ['query'=>['name'=>$file]]); ?>">Remove from folder</a>
            </p>
        </div>
        </div>

        <?php endforeach; ?>
    </div>
    </div>

    <?php endif; ?>

    <hr/>
    </body>
</html>
